name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK AZUL ZULU 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: gradle

    - name: Download gradle jar
      run: gradle wrapper
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: List all tasks
      run: |
        ./gradlew tasks --all
        echo ""
        echo ""
        echo "Alternative:"
        ./gradlew -q :tasks --all
        
    - name: Build with Gradle
      run: ./gradlew build
